#!/usr/bin/env python
"""
Generate docker-compose.yml from strategies.json.

Adding a new strategy:
1. Edit deploy/strategies.json
2. Run: python scripts/generate_compose.py
3. Run: cd deploy && docker compose up -d

Usage:
    python scripts/generate_compose.py
    python scripts/generate_compose.py --strategies deploy/strategies.json --output deploy/docker-compose.yml
"""
import sys
import json
import argparse
from pathlib import Path

project_root = Path(__file__).parent.parent


def generate_compose(strategies_file: Path, output_file: Path):
    """Generate docker-compose.yml from strategies.json."""
    with open(strategies_file) as f:
        config = json.load(f)

    strategies = config.get("strategies", [])
    if not strategies:
        print("ERROR: No strategies defined in strategies.json")
        sys.exit(1)

    # Build YAML
    lines = [
        "# Auto-generated by scripts/generate_compose.py - edit strategies.json instead.",
        "#",
        "# Usage:",
        "#   cd deploy",
        "#   docker compose up -d",
        "#   docker compose logs -f",
        "#   docker compose down",
        "",
        "x-trader-common: &trader-common",
        "  build:",
        "    context: ..",
        "    dockerfile: deploy/Dockerfile",
        "  restart: unless-stopped",
        "  env_file: .env",
        "",
        "services:",
    ]

    for s in strategies:
        sid = s["id"]
        service_name = sid.replace("_", "-").lower()
        strategy = s["strategy"]
        pair = s["pair"]
        timeframe = s["timeframe"]
        risk = s.get("risk_pct", 1.0)
        enabled = s.get("enabled", True)

        lines.append(f"  {service_name}:")
        lines.append(f"    <<: *trader-common")
        lines.append(f"    container_name: {service_name}")
        lines.append(f"    volumes:")
        lines.append(f"      - ../instances/{sid}:/instance")
        lines.append(f"    command: >")
        lines.append(f"      --strategy {strategy}")
        lines.append(f"      --pair {pair}")
        lines.append(f"      --timeframe {timeframe}")
        lines.append(f"      --params-file /instance/config.json")
        lines.append(f"      --instance-dir /instance")
        lines.append(f"      --instance-id {sid}")
        lines.append(f"      --risk {risk}")
        lines.append(f"      --yes")

        if not enabled:
            lines.append(f"    profiles:")
            lines.append(f"      - disabled")

        lines.append("")

    # Monitor service
    lines.extend([
        "  monitor:",
        "    <<: *trader-common",
        "    container_name: trading-monitor",
        "    entrypoint: [\"python\", \"scripts/run_monitor.py\"]",
        "    command: >",
        "      --instances-dir /instances",
        "      --telegram",
        "      --interval 60",
        "    volumes:",
        "      - ../instances:/instances:ro",
    ])

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w") as f:
        f.write("\n".join(lines) + "\n")

    enabled_count = sum(1 for s in strategies if s.get("enabled", True))
    print(f"Generated {output_file}")
    print(f"  {len(strategies)} strategies ({enabled_count} enabled)")
    for s in strategies:
        status = "enabled" if s.get("enabled", True) else "disabled"
        print(f"    [{status}] {s['id']}: {s['strategy']} {s['pair']} {s['timeframe']} @ {s.get('risk_pct', 1.0)}%")


def main():
    parser = argparse.ArgumentParser(description="Generate docker-compose.yml from strategies.json")
    parser.add_argument("--strategies", default=str(project_root / "deploy" / "strategies.json"),
                       help="Path to strategies.json")
    parser.add_argument("--output", default=str(project_root / "deploy" / "docker-compose.yml"),
                       help="Output docker-compose.yml path")

    args = parser.parse_args()
    generate_compose(Path(args.strategies), Path(args.output))


if __name__ == "__main__":
    main()
